### PR TITLE
Fix capitalization of crc32c package

### PR DESCRIPTION
**Pull request by ShubhamAvasthi**
It looks like package names are case-sensitive in Cmake.

This pull request fixes the following errors:

- **Platform:** Linux
  **Caused by:** Line 47

  ```
  CMake Error at CMakeLists.txt:47 (find_package):
    Could not find a package configuration file provided by "crc32c" with any
    of the following names:
  
      crc32cConfig.cmake
      crc32c-config.cmake
  ```

- **Platform:** Linux
  **Caused by:** Line 266

  ```
  CMake Error at CMakeLists.txt:283 (add_executable):
    Target "leveldbutil" links to target "crc32c::crc32c" but the target was
    not found.  Perhaps a find_package() call is missing for an IMPORTED
    target, or an ALIAS target is missing?
  
  
  CMake Error at CMakeLists.txt:114 (add_library):
    Target "leveldb" links to target "crc32c::crc32c" but the target was not
    found.  Perhaps a find_package() call is missing for an IMPORTED target, or
    an ALIAS target is missing?
  
  
  CMake Error at CMakeLists.txt:114 (add_library):
    Target "leveldb" links to target "crc32c::crc32c" but the target was not
    found.  Perhaps a find_package() call is missing for an IMPORTED target, or
    an ALIAS target is missing?
  ```

- **Platform:** Windows
  **Caused by:** Line 266

  ```
  CMake Error at CMakeLists.txt:266 (target_link_libraries):
  -- Generating done (0.1s)
    Target "leveldb" links to:
  
      crc32c::crc32c
  
    but the target was not found.  Possible reasons include:
  
      * There is a typo in the target name.
      * A find_package call is missing for an IMPORTED target.
      * An ALIAS target is missing.
  ```

### CODE REVIEW

**Comment by rbsheth** [comment]
Are you sure the correct package is being found? The hunter version has a lower case name: https://github.com/cpp-pm/crc32c/blob/hunter/CMakeLists.txt#L6

**Comment by ShubhamAvasthi** [comment]
@rbsheth I have verified that this change fixes the errors I mentioned above, allowing me to build the package.
I don't know where the capital C comes from, but I see the same here as well: https://github.com/cpp-pm/hunter/blob/master/examples/crc32c/CMakeLists.txt

**Comment by rbsheth** [comment]
You are correct, that PR has changed the capitalization in CMake. Thanks for this fix!

**Review by rbsheth — APPROVED** [review]

**Comment by ShubhamAvasthi** [comment]
@rbsheth, can you merge this change or add someone who can merge this change as a reviewer?

**Comment by rbsheth** [comment]
@ShubhamAvasthi Merged and released [v1.22-p1](https://github.com/cpp-pm/leveldb/releases/tag/v1.22-p1)

**Pull request merged**
